-- 코드를 입력하세요
WITH TEST AS (SELECT CAR_ID
FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
ORDER BY CAR_ID)

SELECT DISTINCT CAR_ID,
if (CAR_ID in (SELECT CAR_ID
FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
ORDER BY CAR_ID), '대여중','대여 가능') AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC