-- 코드를 입력하세요
SELECT
    FLAVOR
FROM (SELECT
    FLAVOR,
    SUM(TOTAL_ORDER) T
FROM FIRST_HALF
GROUP BY FLAVOR) A
 JOIN
(SELECT
    FLAVOR,
    SUM(TOTAL_ORDER) T
FROM JULY
GROUP BY FLAVOR) B
USING (FLAVOR)
GROUP BY FLAVOR
ORDER BY A.T + B.T DESC
LIMIT 3