-- 코드를 입력하세요
SELECT
    DISTINCT INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) OVER (PARTITION BY INGREDIENT_TYPE) AS TOTAL_ORDER
FROM
    ICECREAM_INFO A
INNER
JOIN
    FIRST_HALF B
ON
    A.FLAVOR = B.FLAVOR
ORDER BY
    2